### ISSUE TITLE
[Tracking] Release Stuff

### ISSUE THREAD

**Issue by equt** [equt/quatrain#5]
## Checklist

- [ ] Prebuild on CI for macOS
- [ ] Auto release with tag message
- [ ] Attach prebuilt binary to release
- [ ] Create a homebrew tap

cc #4
